import matplotlib.pyplot as plt

def apply_dark_plot_theme(self):
        """Set the Matplotlib figure to use a dark theme."""
        self.figure1.patch.set_facecolor('#2b2b2b')
        self.ax1.set_facecolor('#2b2b2b')
        self.ax1.spines['bottom'].set_color('white')
        self.ax1.spines['left'].set_color('white')
        self.ax1.spines['top'].set_color('white')
        self.ax1.spines['right'].set_color('white')
        self.ax1.xaxis.label.set_color('white')
        self.ax1.yaxis.label.set_color('white')
        self.ax1.tick_params(axis='x', colors='white')
        self.ax1.tick_params(axis='y', colors='white')
        self.ax1.title.set_color('white')

        self.figure2.patch.set_facecolor('#2b2b2b')
        self.ax2.set_facecolor('#2b2b2b')
        self.ax2.spines['bottom'].set_color('white')
        self.ax2.spines['left'].set_color('white')
        self.ax2.spines['top'].set_color('white')
        self.ax2.spines['right'].set_color('white')
        self.ax2.xaxis.label.set_color('white')
        self.ax2.yaxis.label.set_color('white')
        self.ax2.tick_params(axis='x', colors='white')
        self.ax2.tick_params(axis='y', colors='white')
        self.ax2.title.set_color('white')

        self.figure2.patch.set_facecolor('#2b2b2b')
        self.ax3.set_facecolor('#2b2b2b')
        self.ax3.spines['bottom'].set_color('white')
        self.ax3.spines['left'].set_color('white')
        self.ax3.spines['top'].set_color('white')
        self.ax3.spines['right'].set_color('white')
        self.ax3.xaxis.label.set_color('white')
        self.ax3.yaxis.label.set_color('white')
        self.ax3.tick_params(axis='x', colors='white')
        self.ax3.tick_params(axis='y', colors='white')
        self.ax3.title.set_color('white')
